/**
 * @namespace rf.calculator.model.metadata
 *
 * Property Example:
 * {
 * 	  "rank": 1,
 * 	  "name": "Mount Everest",
 * 	  "height": 8848,
 * 	  "prominence": 8848,
 * 	  "range": "Mahalangur Himalaya",
 * 	  "coordinates": "27°59'17''N 86°55'31''E",
 * 	  "parent_mountain": "-",
 * 	  "first_ascent": 1953,
 * 	  "countries": "Nepal, China"
 * }
 */
export default [
  {
    key: "Name",
    label: "Name",
    visible: true,
    path: "Name",
    dataType: "sap.ui.model.type.String",
  },
  {
    key: "Rarity",
    label: "Rarity",
    visible: true,
    path: "Rarity",
    dataType: "sap.ui.model.type.Integer",
  },
  {
    key: "Category",
    label: "Category",
    visible: true,
    path: "Category",
    dataType: "sap.ui.model.type.String",
  },
  {
    key: "Difficulty",
    label: "Difficulty",
    visible: true,
    path: "Difficulty",
    dataType: "sap.ui.model.type.Integer",
  },
  {
    key: "atk",
    label: "Attack",
    visible: true,
    path: "atk",
    dataType: "sap.ui.model.type.Integer",
  },
  {
    key: "matk",
    label: "Magic attack",
    visible: true,
    path: "matk",
    dataType: "sap.ui.model.type.Integer",
  },
  {
    key: "def",
    label: "Defence",
    dataType: "sap.ui.model.type.Integer",
    path: "def",
  },
  {
    key: "mdef",
    label: "Magic defence",
    dataType: "sap.ui.model.type.Integer",
    path: "mdef",
  },
  {
    key: "str",
    label: "Strength",
    dataType: "sap.ui.model.type.Integer",
    path: "str",
  },
  {
    key: "vit",
    label: "Vitality",
    dataType: "sap.ui.model.type.Integer",
    path: "vit",
  },
  {
    key: "drainAtk",
    label: "Drain attack",
    dataType: "sap.ui.model.type.Integer",
    path: "drainAtk",
  },
  {
    key: "int",
    label: "Intelligence",
    dataType: "sap.ui.model.type.Integer",
    path: "int",
  },
  {
    key: "parAtk",
    label: "Paralysis attack",
    dataType: "sap.ui.model.type.Integer",
    path: "parAtk",
  },
  {
    key: "crit",
    label: "Critical chance",
    dataType: "sap.ui.model.type.Integer",
    path: "crit",
  },
  {
    key: "drainRes",
    label: "Drain resistance",
    dataType: "sap.ui.model.type.Integer",
    path: "drainRes",
  },
  {
    key: "psnAtk",
    label: "Poison attack",
    dataType: "sap.ui.model.type.Integer",
    path: "psnAtk",
  },
  {
    key: "sickAtk",
    label: "Sickness attack",
    dataType: "sap.ui.model.type.Integer",
    path: "sickAtk",
  },
  {
    key: "slpAtk",
    label: "Sleep attack",
    dataType: "sap.ui.model.type.Integer",
    path: "slpAtk",
  },
  {
    key: "sealAtk",
    label: "Seak attack",
    dataType: "sap.ui.model.type.Integer",
    path: "sealAtk",
  },
  {
    key: "psnRes",
    label: "Poison resistance",
    dataType: "sap.ui.model.type.Integer",
    path: "psnRes",
  },
  {
    key: "sealRes",
    label: "Seal resistance",
    dataType: "sap.ui.model.type.Integer",
    path: "sealRes",
  },
  {
    key: "parRes",
    label: "Paralysis resistance",
    dataType: "sap.ui.model.type.Integer",
    path: "parRes",
  },
  {
    key: "slpRes",
    label: "Sleep resistance",
    dataType: "sap.ui.model.type.Integer",
    path: "slpRes",
  },
  {
    key: "ftgRes",
    label: "Fatigue resistance",
    dataType: "sap.ui.model.type.Integer",
    path: "ftgRes",
  },
  {
    key: "sickRes",
    label: "Sickness resistance",
    dataType: "sap.ui.model.type.Integer",
    path: "sickRes",
  },
  {
    key: "diz",
    label: "Dizzyness attack",
    dataType: "sap.ui.model.type.Integer",
    path: "diz",
  },
  {
    key: "knockAtk",
    label: "Knockback attack",
    dataType: "sap.ui.model.type.Integer",
    path: "knockAtk",
  },
  {
    key: "faintRes",
    label: "Faint resistance",
    dataType: "sap.ui.model.type.Integer",
    path: "faintRes",
  },
  {
    key: "dizRes",
    label: "Dizzyness resistance",
    dataType: "sap.ui.model.type.Integer",
    path: "dizRes",
  },
  {
    key: "critRes",
    label: "Critical chance resistance",
    dataType: "sap.ui.model.type.Integer",
    path: "critRes",
  },
  {
    key: "knockRes",
    label: "Knockback resistance",
    dataType: "sap.ui.model.type.Integer",
    path: "knockRes",
  },
  {
    key: "knock",
    label: "Knockback",
    dataType: "sap.ui.model.type.Integer",
    path: "knock",
  },
  {
    key: "stun",
    label: "Stun",
    dataType: "sap.ui.model.type.Integer",
    path: "stun",
  },
  {
    key: "ftgAtk",
    label: "Fatigue attack",
    dataType: "sap.ui.model.type.Integer",
    path: "ftgAtk",
  },
  {
    key: "faintAtk",
    label: "Faint attack",
    dataType: "sap.ui.model.type.Integer",
    path: "faintAtkfaintAtk",
  },
  {
    key: "upgradeEffct",
    label: "Upgrade effect",
    dataType: "sap.ui.model.type.Integer",
    path: "upgradeEffct",
  },
  {
    key: "effect",
    label: "Effect",
    dataType: "sap.ui.model.type.String",
    path: "effect",
  },
  {
    key: "fireRes",
    label: "Fire resistance",
    dataType: "sap.ui.model.type.Integer",
    path: "fireRes",
  },
  {
    key: "waterRes",
    label: "Water resistance",
    dataType: "sap.ui.model.type.Integer",
    path: "waterRes",
  },
  {
    key: "windRes",
    label: "Wind resistance",
    dataType: "sap.ui.model.type.Integer",
    path: "windRes",
  },
  {
    key: "earthRes",
    label: "Earth resistance",
    dataType: "sap.ui.model.type.Integer",
    path: "earthRes",
  },
];
